# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.hostname = "foo.example.com"
  config.vm.define "redhat-6-x86_64" do |host|
    host.vm.box = "anandbitra/redhat-6.5"
    host.vm.provision "file", source: "Gemfile", destination: "Gemfile"
    host.vm.provision "shell", path: "get_facts.sh", args: "6"
    host.vm.provision "shell", inline: "/sbin/shutdown -h now"
  end
  config.vm.define "redhat-6-x86_64" do |host|
    host.vm.box = "mrlesmithjr/rhel-7"
    host.vm.provision "file", source: "Gemfile", destination: "Gemfile"
    host.vm.provision "shell", path: "get_facts.sh", args: "7"
    host.vm.provision "shell", inline: "/sbin/shutdown -h now"
  end
  config.vm.define "centos-6-x86_64" do |host|
    host.vm.box = "puppetlabs/centos-6.6-64-nocm"
    host.vm.provision "file", source: "Gemfile", destination: "Gemfile"
    host.vm.provision "shell", path: "get_facts.sh", args: "6"
    host.vm.provision "shell", inline: "/sbin/shutdown -h now"
  end
  config.vm.define "centos-7-x86_64" do |host|
    host.vm.box = "puppetlabs/centos-7.0-64-nocm"
    host.vm.provision "file", source: "Gemfile", destination: "Gemfile"
    host.vm.provision "shell", path: "get_facts.sh", args: "7"
    host.vm.provision "shell", inline: "/sbin/shutdown -h now"
  end
end
